### PR TITLE
Fix indentation issues and modeline issue.

### PR DESCRIPTION
**Pull request by crocket**

### CODE REVIEW

**Comment by crocket** [comment]
It fixes https://github.com/pepe/janet.kak/issues/6

**Comment by crocket** [comment]
It fixes https://github.com/pepe/janet.kak/issues/4

**Comment by crocket** [comment]
This pull request is ready.

**Comment by pepe** [comment]
Sorry for the wait. I spent last week caring for all three kids, as they were sick. Yesterday CET I will merge it.

**Review by pepe — APPROVED** [review]
This looks very nice. After I finish the job work, I will check it and merge it. Thank you very much!

**Pull request merged**
